/* r2flutter - MIT - Copyright 2026 - pancake */

#ifndef R2C_DART_CID_H
#define R2C_DART_CID_H

#include <stdbool.h>
#include "dart_version.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
	DART_CID_ILLEGAL = 0,
	DART_CID_NATIVE_POINTER,
	DART_CID_CLASS,
	DART_CID_PATCH_CLASS,
	DART_CID_FUNCTION,
	DART_CID_TYPE_PARAMETERS,
	DART_CID_CLOSURE_DATA,
	DART_CID_FFI_TRAMPOLINE_DATA,
	DART_CID_FIELD,
	DART_CID_SCRIPT,
	DART_CID_LIBRARY,
	DART_CID_NAMESPACE,
	DART_CID_KERNEL_PROGRAM_INFO,
	DART_CID_WEAK_SERIALIZATION_REFERENCE,
	DART_CID_WEAK_ARRAY,
	DART_CID_CODE,
	DART_CID_OBJECT_POOL,
	DART_CID_PC_DESCRIPTORS,
	DART_CID_CODE_SOURCE_MAP,
	DART_CID_COMPRESSED_STACK_MAPS,
	DART_CID_EXCEPTION_HANDLERS,
	DART_CID_CONTEXT,
	DART_CID_CONTEXT_SCOPE,
	DART_CID_SENTINEL,
	DART_CID_SINGLE_TARGET_CACHE,
	DART_CID_UNLINKED_CALL,
	DART_CID_MONOMORPHIC_SMIABLE_CALL,
	DART_CID_CALL_SITE_DATA,
	DART_CID_ICDATA,
	DART_CID_MEGAMORPHIC_CACHE,
	DART_CID_SUBTYPE_TEST_CACHE,
	DART_CID_LOADING_UNIT,
	DART_CID_LANGUAGE_ERROR,
	DART_CID_UNHANDLED_EXCEPTION,
	DART_CID_INSTANCE,
	DART_CID_LIBRARY_PREFIX,
	DART_CID_TYPE_ARGUMENTS,
	DART_CID_TYPE,
	DART_CID_FUNCTION_TYPE,
	DART_CID_RECORD_TYPE,
	DART_CID_TYPE_REF,
	DART_CID_TYPE_PARAMETER,
	DART_CID_CLOSURE,
	DART_CID_MINT,
	DART_CID_DOUBLE,
	DART_CID_FLOAT32X4,
	DART_CID_INT32X4,
	DART_CID_FLOAT64X2,
	DART_CID_RECORD,
	DART_CID_TYPED_DATA,
	DART_CID_EXTERNAL_TYPED_DATA,
	DART_CID_TYPED_DATA_VIEW,
	DART_CID_CAPABILITY,
	DART_CID_RECEIVE_PORT,
	DART_CID_SEND_PORT,
	DART_CID_STACK_TRACE,
	DART_CID_SUSPEND_STATE,
	DART_CID_REGEXP,
	DART_CID_WEAK_PROPERTY,
	DART_CID_WEAK_REFERENCE,
	DART_CID_FUTURE_OR,
	DART_CID_USER_TAG,
	DART_CID_TRANSFERABLE_TYPED_DATA,
	DART_CID_MAP,
	DART_CID_CONST_MAP,
	DART_CID_SET,
	DART_CID_CONST_SET,
	DART_CID_ARRAY,
	DART_CID_IMMUTABLE_ARRAY,
	DART_CID_GROWABLE_OBJECT_ARRAY,
	DART_CID_STRING,
	DART_CID_ONE_BYTE_STRING,
	DART_CID_TWO_BYTE_STRING,
	DART_CID_NUM_PREDEFINED_CIDS,
	DART_CID_KIND_COUNT
} DartCidKind;

const char *dart_cid_kind_name(DartCidKind kind);
int dart_cid_get(const DartVerLayout *layout, DartCidKind kind);
bool dart_cid_is(const DartVerLayout *layout, int cid, DartCidKind kind);
bool dart_cid_is_string(const DartVerLayout *layout, int cid);
bool dart_cid_is_array(const DartVerLayout *layout, int cid);
int dart_cid_typed_data_internal_base(const DartVerLayout *layout);
int dart_cid_typed_data_internal_limit(const DartVerLayout *layout);
int dart_cid_typed_data_stride(const DartVerLayout *layout);
bool dart_cid_typed_data_internal_kind(const DartVerLayout *layout, int cid, int *out_rem);

#ifdef __cplusplus
}
#endif

#endif // R2C_DART_CID_H
