#ifndef R2FLUTTER_VERSION_H
#define R2FLUTTER_VERSION_H

#define R2FLUTTER_VERSION "0.3.6"
#define R2FLUTTER_VERSION_MAJOR 0
#define R2FLUTTER_VERSION_MINOR 3
#define R2FLUTTER_VERSION_PATCH 6

#endif
