#ifndef R2FLUTTER_VERSION_H
#define R2FLUTTER_VERSION_H

#define R2FLUTTER_VERSION "0.4.0"
#define R2FLUTTER_VERSION_MAJOR 0
#define R2FLUTTER_VERSION_MINOR 4
#define R2FLUTTER_VERSION_PATCH 0

#endif
