#!/usr/bin/env bash
set -euo pipefail

# Generate r2flutter/offsets.json for the detected snapshot hash and Dart version.
# Usage: scripts/gen_offsets.sh <libdir>

if [ $# -lt 1 ]; then
  echo "Usage: $0 <libdir-with-libapp.so-and-libflutter.so>" >&2
  exit 1
fi

LIBDIR="$1"
LIBAPP="$LIBDIR/libapp.so"
LIBFLUTTER="$LIBDIR/libflutter.so"

if [ ! -f "$LIBAPP" ] || [ ! -f "$LIBFLUTTER" ]; then
  echo "Missing libapp.so or libflutter.so in $LIBDIR" >&2
  exit 1
fi

SNAPSHOT_DATA_VADDR=$(readelf -Ws "$LIBAPP" | grep '_kDartVmSnapshotData$' | awk '{print "0x"$2}' | head -n 1)
if [ -z "$SNAPSHOT_DATA_VADDR" ]; then
    echo "Failed to find _kDartVmSnapshotData symbol in $LIBAPP" >&2
    exit 1
fi

HASH_OFFSET=$((SNAPSHOT_DATA_VADDR+20))

HASH=$(dd if="$LIBAPP" bs=1 skip=$((HASH_OFFSET)) count=32 2>/dev/null | tr -dc '0-9a-f' | head -c 32)
if [ -z "$HASH" ]; then
  echo "Failed to extract snapshot hash from $LIBAPP" >&2
  exit 1
fi

VERLINE="$(strings -a "$LIBFLUTTER" | sed -n 's/^\([0-9]\+\.[0-9]\+\.[0-9]\+\) (stable).*/\1/p' | head -n1)"
if [ -z "$VERLINE" ]; then
  echo "Warning: Cannot determine Dart version from $LIBFLUTTER; continuing with hash only" >&2
fi

echo "Detected snapshot hash: $HASH, dart version: ${VERLINE:-unknown}"

# Prepare minimal offsets JSON with reasonable defaults; future versions of this
# generator can curl dart-lang/sdk sources and compute more fields.
OUTJSON="offsets.json"
mkdir -p "$(dirname "$OUTJSON")"

cat > "$OUTJSON" <<JSON
{
  "arch": "arm64",
  "hashes": {
    "$HASH": {
      "compressed_word_size": 4,
      "heap_object_tag": 1,
      "notes": "Autogenerated skeleton for $VERLINE; refine via SDK source parsing"
    }
  }
}
JSON

echo "Wrote $OUTJSON"
