#!/usr/bin/env bash
set -euo pipefail

# Generate r2flutter/offsets.json for the detected snapshot hash and Dart version.
# Usage: scripts/gen_offsets.sh <libdir>

if [ $# -lt 1 ]; then
  echo "Usage: $0 <libdir-with-libapp.so-and-libflutter.so>" >&2
  exit 1
fi

LIBDIR="$1"
LIBAPP="$LIBDIR/libapp.so"
LIBFLUTTER="$LIBDIR/libflutter.so"

if [ ! -f "$LIBAPP" ] || [ ! -f "$LIBFLUTTER" ]; then
  echo "Missing libapp.so or libflutter.so in $LIBDIR" >&2
  exit 1
fi

# Read 32 ASCII bytes at vm snapshot data + 20 (vm data symbol vaddr is 0x200 in many builds)
# We don't depend on r2 here; we assume symbol location is at 0x200 as in typical libapp.so.
# If needed, this can be improved to query r2 isj for the exact address.
HASH="$(dd if="$LIBAPP" bs=1 skip=$((512+20)) count=32 2>/dev/null | tr -dc '0-9a-f' | head -c 32)"
if [ -z "$HASH" ]; then
  echo "Failed to extract snapshot hash from $LIBAPP" >&2
  exit 1
fi

VERLINE="$(strings -a "$LIBFLUTTER" | sed -n 's/^\([0-9]\+\.[0-9]\+\.[0-9]\+\) (stable).*/\1/p' | head -n1)"
if [ -z "$VERLINE" ]; then
  echo "Warning: Cannot determine Dart version from $LIBFLUTTER; continuing with hash only" >&2
fi

echo "Detected snapshot hash: $HASH, dart version: ${VERLINE:-unknown}"

# Prepare minimal offsets JSON with reasonable defaults; future versions of this
# generator can curl dart-lang/sdk sources and compute more fields.
OUTJSON="r2flutter/offsets.json"
mkdir -p "$(dirname "$OUTJSON")"

cat > "$OUTJSON" <<JSON
{
  "arch": "arm64",
  "hashes": {
    "$HASH": {
      "compressed_word_size": 4,
      "heap_object_tag": 1,
      "notes": "Autogenerated skeleton for $VERLINE; refine via SDK source parsing"
    }
  }
}
JSON

echo "Wrote $OUTJSON"
