name: ci

env:
  R2V: 6.1.4

on:
  push:
  pull_request:


jobs:
  build-linux24:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - name: Installing radare2 ${{ env.R2V }}
      uses: radareorg/github-actions@v2
      with:
        version: ${{ env.R2V }}
    - name: Building r2flutter
      run: make && make user-install
    - name: Basic Testing
      run: make test
    - name: Radare Testing
      run: r2r test/db/cmd
    - name: Radare Extras Testing
      run: r2r test/db/extras
