name: ci

env:
  R2V: 6.1.0

on:
  push:
  pull_request:


jobs:
  build-linux24:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - name: Installing radare2
      run: |
        wget https://github.com/radareorg/radare2/releases/download/${{env.R2V}}/radare2_${{env.R2V}}_amd64.deb
        wget https://github.com/radareorg/radare2/releases/download/${{env.R2V}}/radare2-dev_${{env.R2V}}_amd64.deb
        sudo dpkg -i radare2_${{env.R2V}}_amd64.deb
        sudo dpkg -i radare2-dev_${{env.R2V}}_amd64.deb
    - name: Building fluor2
      run: make
    - name: Basic Testing
      run: make test
    - name: Radare Testing
      run: r2r -j1 -t 30 test/db/cmd
    - name: Radare Extras Testing
      run: r2r -j1 -t 30 test/db/extras
